### ISSUE TITLE
Issue with Mobile View of highlighted code

### ISSUE THREAD

**Issue by vishal2612200** [EnlighterJS/EnlighterJS#100]
Part of the code inside the highlighter get hide on the mobile device,i.e There is some responsivity issue on Mobile device.
Here is the screenshot of the problem.
![Screenshot from 2020-04-19 04-47-19](https://user-images.githubusercontent.com/37480057/79673632-02adb600-81f9-11ea-858b-1269c8490e1c.png)

**Comment by AndiDittrich** [comment]
hi @vishal2612200 

i cannot debug the issue without a link to your website.

currently i assume that it's not a bug - it seems to be caused by line `20` - the regular css line-breaking cannot be applied.

maybe you should set the line breaking behaviour to "scroll" - this provides especially on mobile devices a much better useability

**Comment by vishal2612200** [comment]
Thanks @AndiDittrich, you were right line breaking was not working fine on the page but after the changing behavior to scroll, Everything gets settled at the right place.

I am closing this issue now, As Problem has been resolved now :)
