### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by kevcodez** [EnlighterJS/EnlighterJS#26]
I added Kotlin support with this [commit](https://github.com/kevcodez/EnlighterJS/commit/ccd83f1492dd22ec8e6d8ac0e2157464c5c62dd8).

I have seen that you want to rewrite the languages for v3. Is there a branch or repo? I would help you add it to the new format, I just don't know where it is. Is this repo even being maintained anymore?

Regards,
Kevin

**Comment by AndiDittrich** [comment]
Dear kevcodez,

thanks for your contribution! please create a pull request so i can merge your commit easier :)
EnlighterJS v3 is no released yet. The repository is still private because of some incompatible changes in-between. 
EnlighterJS v2 is maintained but not active developed anymore. the upcoming major release is a drop-in-replacement.

br. Andi

**Comment by kevcodez** [comment]
Hey Andi,

once you publish the repository, you may mention me here aswell if you need help migrating the Kotlin syntax.

Regards,
Kevin

**Comment by AndiDittrich** [comment]
Hi Kevin,
of course, i will do this, thanks!

v3 was projected for Q1 2016... but i didn't head enough time to convert the themes...everything else (DOM, tokenizer, languages) is ready... i hope to release in Q3 2017

br Andi

**Comment by AndiDittrich** [comment]
## Kotlin Example ##

![enlighterjs_kotlin](https://user-images.githubusercontent.com/1474107/42733262-a8c63308-882e-11e8-8a7f-bcb40ff334df.png)
