### ISSUE TITLE
Wrong Python Highlighting in Gutenberg

### ISSUE THREAD

**Issue by predictedblog** [EnlighterJS/EnlighterJS#42]
Hey there,

I found a strange behaviour when writing two forward slashes in one line of Python code. Enlighter appears to think that now it's a java comment or something because it marks the area between these two forward slashes green and even ignores a python comment sign (#) in between them. 

![Picture](https://user-images.githubusercontent.com/44035142/46824269-9dba0a00-cd90-11e8-89d4-6e7dc4088eb3.jpg)

As you can see in the Image, the first line demonstrates the bug, the second and third work properly (there is only one forward slash in them).

WordPress Version 4.9.8 (Using the Gutenberg plugin)
Enlighter Version 3.8.1

Regards

**Comment by AndiDittrich** [comment]
Hi Sebastian,

thanks for your report. the issue is related to the Highlighting Engine of EnlighterJS2.
The issue does not appear in EnlighterJS3.

you can try out the [experimental integration](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat) which adds EnlighterJS3 to the current Enlighter plugin.

**EnlighterJS 3 Example**
![enlighterjs2_error_python](https://user-images.githubusercontent.com/1474107/46828144-ca731f00-cd9a-11e8-8eb0-22e1f0e3ad1d.png)

The release of Enlighter v4 WordPress Plugin (including EnlighterJS3) is projected for this year.

best regards, Andi

**Comment by predictedblog** [comment]
Hi Andi,

ok thats good news! For now I will stay with the old version and just avoid making two forward slashes in one line. 

Regards, Sebastian
