### ISSUE TITLE
Requesting PowerShell Highlighting

### ISSUE THREAD

**Issue by danchemistruck** [EnlighterJS/EnlighterJS#67]
I love the simplicity of this plugin! All the code I post is Windows PowerShell, and it would be great to have native support built in.

**Comment by AndiDittrich** [comment]
Hi  @danchemistruck 

PowerShell has already been added to EnlighterJS v3 - see https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/powershell.js

**Comment by danchemistruck** [comment]
I'm using the WordPress plugin and it looks like PowerShell is missing in the LanguageManager.php file for the plugin. Is there any documentation on how to update the plugin to make PowerShell an option?

**Comment by AndiDittrich** [comment]
it's not missing... i thought your issue was related to `EnlighterJS` and not to `Enlighter WordPress Plugin` - please keep care of the terminology and the versioning schemes...

to try EnlighterJS v3 with the current WordPress Plugin v3 there is an experimental plugin available: https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat
